routes/web.php
<?php

use App\Http\Controllers\ExperienceController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SkillController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;


Route::get('/', function () {
    return redirect('/index');
});

// frontend
Route::get('index', [FrontController::class, 'index'])->name('index');
Route::get('port_project', [FrontController::class, 'port_project'])->name('port_project');


// experiences
Route::resource('projects', ProjectController::class);

Route::resource('experiences', ExperienceController::class);

//skills
Route::resource('skills', SkillController::class);


Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', function () {
        return view('dashboard.dashboard.index');
    })->name('dashboard');

    // User CRUD
    Route::resource('users', UserController::class);
    Route::resource('projects', ProjectController::class);
});

app/Models/Skill.php
<?php

namespace App\Models;

use App\Observers\SkillObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    use HasFactory;

     protected static function boot() {
        parent::boot();
        static::observe(SkillObserver::class);
    }

}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use App\Models\Skill;
use Illuminate\Http\Request;

class SkillController extends Controller
{
    public function index()
    {
        $skills = Skill::get();
        return view('dashboard.skill.index', compact('skills'));
    }

    public function create()
    {
        return view('dashboard.skill.create');
    }

    public function store(Request $request)
    {
        $skill = new Skill;
        $skill->name = $request->name;
        $skill->status = $request->status;
        $skill->save();
        return redirect('/skills')->with(['success' => 'Project has been Created.']);
    }

    public function show($id)
    {
        $skill = Skill::find($id);
        return view('dashboard.skill.show', compact('skill'));
    }

    public function edit($id)
    {
        $skill = Skill::find($id);
        return view('dashboard.skill.edit', compact('skill'));
    }
    public function update(Request $request, $id)
    {
        $skill = Skill::find($id);
        $skill->name = $request->name;
        $skill->status = $request->status;
        $skill->update();
        return redirect('/skills')->with(['success' => 'Project has been updated.']);
    }

    public function destroy($id)
    {
        Skill::find($id)->delete();
        return redirect('/skills')->with(['success' => 'Project has been Deleted.']);
    }
}

resources/views/dashboard/skill/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Add Skill
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css"
        integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Add Skill</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('skills.index') }}">Skills</a>
                </li>
                <li class="active">
                    <strong>Add Skill</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('skills.index') }}" class="btn btn-warning mt-3" id="save-data">
            <span class="fa fa-arrow-left"></span>
            Back
        </a>
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save </button>
        </div>
    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('skills.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Skills Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-md-12">

                                    <div class="form-group @error('name') has-error @enderror">
                                        <label for="name">Name <span class="text-danger">*</span></label>
                                        <input type="text" placeholder="Enter name" class="form-control" name="name"
                                            id="name" value="{{ old('name') }}">
                                        @error('name')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('status') has-error @enderror">
                                        <label for="status">Status <span class="text-danger">*</span></label>
                                        <select class="form-control" name="status" id="state">
                                            <option selected disabled>Select</option>
                                            <option value="active">active</option>
                                            <option value="inactive">inactive</option>
                                            @error('status')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Uploaded Photo</h5>
                        </div>
                        <div class="ibox-content">
                            <input type="file" class="dropify" name="file" />
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"
        integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.dropify').dropify();

        $('.datepicker').datepicker({
            // format: 'yyyy-mm-dd',
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });

        $(document).on('click', '#save-data', function() {
            $('form').submit();
        })
    </script>

@endsection

resources/views/dashboard/skill/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Edit Skill
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css"
        integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection
@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Edit Skill</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('skills.index') }}">Skills</a>
                </li>
                <li class="active">
                    <strong>Edit Skill </strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('skills.index') }}" class="btn btn-warning mt-3" id="save-data">
                <span class="fa fa-arrow-left"></span>
                Back
            </a>
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save </button>
        </div>

    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('skills.update', $skill->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Skills Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-md-12">

                                    <div class="form-group @error('name') has-error @enderror">
                                        <label for="name">Name <span class="text-danger">*</span></label>
                                        <input type="text" placeholder="Enter name" class="form-control" name="name"
                                            id="name" value="{{ $skill->name }}">
                                        @error('name')
                                            <span class=" text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('status') has-error @enderror">
                                        <label for="status">Status <span class="text-danger">*</span></label>
                                        <select class="form-control" name="status" id="state">
                                            <option selected disabled>Select</option>
                                            <option value="active" {{ $skill->status =='active'?'selected':''}}>active</option>
                                            <option value="inactive" {{ $skill->status =='inactive'?'selected':''}}>inactive</option>
                                            @error('status')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                     <div class="ibox-title">
                     <h5>Uploaded Photo</h5>
                       </div>
                   <div class="ibox-content">
                <input type="file" class="dropify" name="file" data-default-file="{{ asset('skill_uploads/skills/'.$skill->image) }}" />
               </div>
            </div>
           </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"
        integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.dropify').dropify();

        $('.datepicker').datepicker({
            // format: 'yyyy-mm-dd',
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });

        $(document).on('click', '#save-data', function() {
            $('form').submit();
        })
    </script>

@endsection

resources/views/dashboard/skill/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Users
@endsection

@section('css')
    <link href="{{ asset('asset/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endsection

@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading justify-content-">
        <div class="col-lg-11">
            <h2>Add</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>

                <li class="active">
                    <strong>Skills </strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-1">
            <a href="{{ route('skills.create') }}" class="btn btn-primary mt-3">
                <span class="fa fa-plus"></span>
                Add </a>
        </div>
    </div>
@endsection

@section('content')

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Users List
                        </h5>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover users-table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Image</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($skills as $skill)
                                        <tr>
                                            <td>{{ $skill->name }}</td>
                                            <td>

                                                <img src="{{ asset('skill_uploads/skills/'.$skill->image) }}" alt="" height="60" width="60">
                                            </td>
                                            <td>
                                                @if ($skill->status == 'active')
                                                    <span class="label label-primary">Active</span>
                                                @else
                                                    <span class="label label-danger">In-Active</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{ route('skills.show', $skill->id) }}"
                                                        class="btn-white btn btn-xs">View</a>

                                                    <a href="{{ route('skills.edit', $skill->id) }}"
                                                        class="btn-white btn btn-xs">Edit</a>

                                                    <a href="javascript:;" data-skill-id="{{ $skill->id }}"
                                                         class="btn-white btn btn-xs delete-skill">Delete</a>

                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    {{-- Datatable --}}
    <script src=" {{ asset('asset/js/plugins/dataTables/datatables.min.js') }}"></script>

    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function() {
            $('.users-table').DataTable();

            @if (session('success'))
                toastr.success('{{ session('success') }}', 'Success');
            @endif

            $('.delete-skill').click(function() {

                let skillId = $(this).data('skill-id');

                // Generate Token method 1
                // let token = $("meta[name='csrf-token']").attr("content");

                // Generate Token method 2
                let token = '{{ csrf_token() }}';

                let url = '{{ route('skills.destroy', ':id') }}';
                url = url.replace(':id', skillId);

                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this data!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                }, function() {

                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {
                            "_token": token,
                            "_method": 'DELETE',

                        },
                        success: function() {
                            swal("Deleted!", "skill has been deleted.",
                                "success");
                            setTimeout(() => {
                                location.reload();
                            }, 3000);
                        }
                    });

                });
            });

        });
    </script>
@endsection

resources/views/dashboard/skill/show.blade.php
@extends('layouts.dashboard')

@section('title')
Show Skill
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css"
        integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection

@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Show Skill</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('skills.index') }}">Skills</a>
                </li>
                <li class="active">
                    <strong>Show Skill </strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('skills.index') }}" class="btn btn-warning mt-3" id="save-data">
                <span class="fa fa-arrow-left"></span>
                Back
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            {{-- <form action="{{ route('skills.show',$skill->id) }}" method="post"> --}}
            <form action="{{ route('skills.show', $skill->id) }}" method="post" enctype="multipart/form-data">

                @csrf

                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Skills Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-md-12">

                                    <div class="form-group @error('name') has-error @enderror">
                                        <label for="name">Name <span class="text-danger">*</span></label>
                                        <input type="text" placeholder="Enter name" class="form-control" name="name"
                                            id="name" value="{{ $skill->name }}">
                                        @error('name')
                                            <span class=" text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                    <div class="col-lg-3">
                                         <div class="ibox float-e-margins">
                                          <div class="ibox-title">
                                          <h5>Uploaded Photo</h5>
                                            </div>
                                        <div class="ibox-content">
                                     <input type="file" class="dropify" name="file" data-default-file="{{ asset('skill_uploads/skills/'.$skill->image) }}" />
                                    </div>
                                 </div>
                        </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('Status') has-error @enderror">
                                        <label for="Status">Status <span class="text-danger">*</span></label>
                                        <select class="custom-select" name="status">
                                            <option selected>Status</option>
                                            <option value="1" {{ $skill->status =='active'?'selected':''}}>Active</option>
                                            <option value="2" {{ $skill->status =='inactive'?'selected':''}}>In Active</option>
                                          </select>
                                        @error('Status')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"
        integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.dropify').dropify();

        $('.datepicker').datepicker({
            // format: 'yyyy-mm-dd',
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });

        $(document).on('click', '#save-data', function() {
            $('form').submit();
        })
    </script>

@endsection