routes/web.php
<?php

use App\Http\Controllers\ExperienceController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SkillController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;


Route::get('/', function () {
    return redirect('/index');
});

// frontend
Route::get('index', [FrontController::class, 'index'])->name('index');
Route::get('port_project', [FrontController::class, 'port_project'])->name('port_project');


// experiences
Route::resource('projects', ProjectController::class);

Route::resource('experiences', ExperienceController::class);

//skills
Route::resource('skills', SkillController::class);


Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', function () {
        return view('dashboard.dashboard.index');
    })->name('dashboard');

    // User CRUD
    Route::resource('users', UserController::class);
    Route::resource('projects', ProjectController::class);
});

app/Models/Project.php
<?php

namespace App\Models;

use App\Observers\ProjectObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    protected static function boot()
    {
        parent::boot();
        static::observe(ProjectObserver::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Projects\StoreProject;
use App\Models\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    public function index()
    {
        $projects = Project::get();
        return view('dashboard.project.index', compact('projects'));
    }

    public function create()
    {
        return view('dashboard.project.create');
    }

    public function store(StoreProject $request)
    {
        $project = new Project;
        $project->title = $request->title;
        $project->visit = $request->visit;
        $project->gitlab = $request->gitlab;
        $project->description = $request->description;
        $project->status = $request->status;
        $project->save();

        return redirect('/projects')->with(['success' => 'Project has been created.']);
    }

    public function show($id)
    {
        $project = Project::find($id);
        return view('dashboard.project.show', compact('project'));
    }

    public function edit($id)
    {
        $project = Project::find($id);
        return view('dashboard.project.edit', compact('project'));
    }


    public function update(Request $request, $id)
    {
        $project = Project::find($id);
        $project->title = $request->title;
        $project->visit = $request->visit;
        $project->gitlab = $request->gitlab;
        $project->description = $request->description;
        $project->status = $request->status;
        $project->save();

        return redirect('/projects')->with(['success' => 'Project has been updated.']);
    }

    public function destroy($id)
    {
        Project::find($id)->delete();

        return redirect('/projects')->with(['success' => 'Project has been deleted.']);
    }
}

resources/views/dashboard/project/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Add
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('breadcrum')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Add Project</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">Home</a>
            </li>
            <li>
                <a href="{{ route('projects.index') }}">Project</a>
            </li>
            <li class="active">
                <strong>Add Project</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        <a href="{{ route('projects.index') }}" class="btn btn-warning mt-3" id="save-data">
        <span class="fa fa-arrow-left"></span>
        Back
        </a>
        <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save </button>
    </div>
</div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('projects.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Personal Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group @error('title') has-error @enderror">
                                            <label for="title">Title <span class="text-danger">*</span></label>
                                            <input type="text" placeholder="Enter title" class="form-control" name="title" id="title" value="{{ old('title') }}">
                                            @error('title')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group @error('visit') has-error @enderror">
                                            <label for="visit">Visit <span class="text-danger">*</span></label>
                                            <input type="text" placeholder="Enter url" class="form-control" name="visit" id="visit" value="{{ old('visit') }}">
                                            @error('title')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group @error('gitlab') has-error @enderror">
                                            <label for="gitlab">Gitlab <span class="text-danger">*</span></label>
                                            <input type="text" placeholder="Enter gitlab url" class="form-control" name="gitlab" id="gitlab" value="{{ old('gitlab') }}">
                                            @error('title')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>


                                <div class="col-md-12">
                                    <div class="form-group @error('status') has-error @enderror">
                                        <label for="status">Status <span class="text-danger">*</span></label>
                                        <select class="form-control" name="status" id="state">
                                            <option selected disabled>Select</option>
                                            <option value="active">active</option>
                                            <option value="inactive">inactive</option>
                                            @error('status')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                        </select>
                                    </div>
                                </div>

                                    <div class="col-md-12">
                                        <div class="form-group @error('description') has-error @enderror">
                                            <label for="description">Description <span class="text-danger">*</span></label>
                                            <textarea class="form-control summernote" name="description" id="description">
                                            </textarea>
                                            @error('description')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>
                                    {{-- <div class="col-md-12">
                                        <div class="form-group @error('description') has-error @enderror">
                                            <label for="description">Description <span class="text-danger">*</span></label>
                                            <textarea class="form-control summernote" name="description" id="description">
                                            </textarea>
                                            @error('description')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div> --}}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Uploaded Photo</h5>
                        </div>
                        <div class="ibox-content">
                            <input type="file" class="dropify" name="file" />
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.dropify').dropify();

        $('.datepicker').datepicker({
            // format: 'yyyy-mm-dd',
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });

        $(document).on('click', '#save-data', function(){
            $('form').submit();
        })


    </script>

@endsection

resources/views/dashboard/project/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Edit
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Edit Project</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('projects.index') }}">Project</a>
                </li>
                <li class="active">
                    <strong>Edit Project</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('projects.index') }}" class="btn btn-warning mt-3" id="save-data">
            <span class="fa fa-arrow-left"></span>
            Back
            </a>
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save </button>
        </div>
    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('projects.update', $project->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="col-lg-9">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h3>Projects Details</h3>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group @error('title') has-error @enderror">
                                                <label for="title">Title <span class="text-danger">*</span></label>
                                                <input type="text" placeholder="Enter title" class="form-control" name="title" id="title" value="{{$project->title }}">
                                                @error('title')
                                                    <span class="text-danger"> {{ $message }} </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group @error('visit') has-error @enderror">
                                                <label for="visit">Visit <span class="text-danger">*</span></label>
                                                <input type="text" placeholder="Enter visit url" class="form-control" name="visit" id="visit" value="{{$project->visit }}">
                                                @error('title')
                                                    <span class="text-danger"> {{ $message }} </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group @error('gitlab') has-error @enderror">
                                                <label for="gitlab">gitlab <span class="text-danger">*</span></label>
                                                <input type="text" placeholder="Enter gitlab url" class="form-control" name="gitlab" id="gitlab" value="{{$project->gitlab }}">
                                                @error('title')
                                                    <span class="text-danger"> {{ $message }} </span>
                                                @enderror
                                            </div>
                                        </div>


                                        <div class="col-md-12">
                                            <div class="form-group @error('status') has-error @enderror">
                                            <label for="status"> Status <span class="text-danger">*</span></label>
                                            <select class="form-control" name="status" id="status">
                                                <option>Select</option>
                                                <option value="active" {{ $project->status == 'active' ? 'selected' : '' }}>Active</option>
                                                <option value="inactive" {{ $project->status == 'inactive' ? 'selected' : '' }}>Inactive</option>
                                            </select>
                                            </div>
                                        </div>


                                        <div class="col-md-12">
                                            <div class="form-group @error('description') has-error @enderror">
                                                <label for="description">Description <span class="text-danger">*</span></label>
                                                <input type="description" class="form-control" placeholder="Enter description" name="description" id="description" value="{{ $project->description }}">
                                                @error('description')
                                                    <span class="text-danger"> {{ $message }} </span>
                                                @enderror
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                </div>

                    <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Uploaded Photo</h5>
                        </div>
                        <div class="ibox-content">
                            <input type="file" class="dropify" name="file" name="file" data-default-file="{{ asset('project-uploads/projects/'.$project->photo) }}"/>
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.dropify').dropify();

        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });

        $(document).on('click', '#save-data', function(){
            $('form').submit();
        });


    </script>

@endsection

resources/views/dashboard/project/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Project
@endsection

@section('css')
    <link href="{{ asset('asset/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endsection

@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2> Add Project </h2>
            <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">Home</a>
            </li>
            <li class="active">
                <a href="{{ route('projects.index') }}">
                    <strong> Add Project </strong>
                </a>
            </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('projects.create') }}" class="btn btn-primary mt-3">
                <span class="fa fa-plus"></span>
                Add </a>
        </div>
    </div>
@endsection

@section('content')

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Projects List
                        </h5>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover users-table">
                                <thead>
                                    <tr>
                                        <th>Photo</th>
                                        <th>Title</th>
                                        <th>Visit</th>
                                        <th>Gitlab</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($projects as $project)
                                        <tr>
                                            <td>
                                                <img src="{{ asset('project-uploads/projects/'.$project->photo) }}" alt="" height="60" width="60">
                                            </td>
                                            <td>{{ $project->title }}</td>
                                            <td>{{ $project->visit }}</td>
                                            <td>{{ $project->gitlab }}</td>
                                            <td>
                                                @if ($project->status == 'active')
                                                    <span class="label label-primary">Active</span>
                                                @else
                                                    <span class="label label-danger">In-Active</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{ route('projects.show', $project->id) }}"
                                                        class="btn-white btn btn-xs">View</a>

                                                    <a href="{{ route('projects.edit', $project->id) }}"
                                                        class="btn-white btn btn-xs">Edit</a>

                                                    <a href="javascript:;" data-project-id="{{ $project->id }}"
                                                        class="btn-white btn btn-xs delete-project">Delete</a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    {{-- Datatable --}}
    <script src=" {{ asset('asset/js/plugins/dataTables/datatables.min.js') }}"></script>

    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function() {
            $('.users-table').DataTable();

            @if (session('success'))
                toastr.success('{{ session('success') }}', 'Success');
            @endif

            $('.delete-project').click(function() {

                let userId = $(this).data('project-id');

                // Generate Token method 1
                // let token = $("meta[name='csrf-token']").attr("content");

                // Generate Token method 2
                let token = '{{ csrf_token() }}';

                let url = '{{ route('projects.destroy', ':id') }}';
                url = url.replace(':id', userId);

                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this data!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                }, function() {

                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {
                            "_token": token,
                            "_method": 'DELETE',

                        },
                        success: function() {
                            swal("Deleted!", "Project has been deleted.",
                                "success");
                            setTimeout(() => {
                                location.reload();
                            }, 3000);
                        }
                    });

                });
            });

        });
    </script>
@endsection